apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  ports:
  - port: 3000
    targetPort: 3000  # Added to explicitly map to container port
    protocol: TCP
    nodePort: 30007   # Optional: specify a port in 30000-32767 range
  type: NodePort      # Changed from ClusterIP to NodePort
  selector:
    role: frontend